<?php

/**
 * @file
 * Preprocess functions for First Step Subtheme.
 */

/**
 * Prepares variables for the html.html.twig template.
 */
function first_step_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')->getPath('stanford_basic');
}

function first_step_subtheme_preprocess_config_pages__stanford_local_footer(&$variables) {
  try {
    $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  }
  catch (Exception $e) {
    $variables['is_front'] = FALSE;
  }

  // Ensure the cache varies correctly.
  $variables['#cache']['contexts'][] = 'url.path.is_front';
}

