<?php

/**
 * @file
 * Preprocess functions for First Step Subtheme.
 */

/**
 * Prepares variables for the html.html.twig template.
 */
function first_step_subtheme_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')->getPath('stanford_basic');
}

function first_step_subtheme_preprocess_pattern_localfooter(&$variables) {
  try {
    $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  }
  catch (Exception $e) {
    $variables['is_front'] = FALSE;
  }

  // Ensure the cache varies correctly.
  $variables['#cache']['contexts'][] = 'url.path.is_front';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function first_step_subtheme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'first_step_subtheme_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

/**
 * Add path based page name template suggestions.
 */
function first_step_subtheme_theme_suggestions_page_alter(&$suggestions, $variables) {
  $path = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($path);

  $path_alias = trim($alias, '/');
  $path_alias = str_replace('/', '_', $path_alias);
  $path_alias = str_replace('-', '_', $path_alias);

  $suggestions[] = 'page__'.$path_alias;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function first_step_subtheme_preprocess_page__resources_directory(&$variables) {
  stanford_basic_preprocess_page__search($variables);

  // Replace the library if it exists.
  foreach ($variables['#attached']['library'] as &$library) {
    if ($library === 'stanford_basic/algolia-search') {
      $library = 'first_step_subtheme/algolia-search';
    }
  }
}
